name:           Retired fields
description:    A temporary plugin holding retired or orphaned metadata fields
version:        1.0.0
author_name:    'Endevver, LLC'
author_link:    http://endevver.com
id:             RetiredFields
key:            RetiredFields

unused_meta_fields:
    blog:
        - include_system
        - current_style
        - sajksdhksdhjk
    category:
        - field.event_all_day
        - field.event_end
        - field.event_featured
        - field.event_location
        - field.event_location_address
        - field.event_multimedia_category
        - field.event_start
        - field.event_tag
        - field.featured
        - field.main_image
    entry:
        - field.asset_field_test
        - field.attract_entry_id
        - field.audioid
        - field.completelydifferentname
        - field.embed_video_player
        - field.end
        - field.event3_speaker
        - field.event5_host
        - field.event_multimedia_category
        - field.event_tag
        - field.eventdate
        - field.favorite_genentech_clothing_item_or_memorabilia
        - field.featured
        - field.has_video
        - field.imagegalleryid
        - field.location
        - field.parent_event
        - field.photo_of_the_week
        - field.poll
        - field.profile_department
        - field.related_1
        - field.related_2
        - field.related_3
        - field.related_link1
        - field.related_link1_text
        - field.related_link2
        - field.related_link2_text
        - field.related_link3
        - field.related_link3_text
        - field.related_links
        - field.related_story1
        - field.related_story2
        - field.related_story3
        - field.sidebar_paragraph_title1
        - field.sidebar_paragraph_title2
        - field.sidebar_title
        - field.start
        - field.stats
        - field.story_type
        - field.submitter
        - field.test_text_field
        - field.time_at_genentech
        - field.video_of_the_week
        - field.video_player_size
        - field.videoid
        - field.youtube

obsolete_meta_fields:
    blog:
        - theme_mode
        - theme_meta
        - template_set_language
    category:
        - field.all_day
        - field.end
        - field.event_location
        - field.event_tag
        - field.location_address
        - field.location_name
        - field.start
    entry:
        - field.activity_all_day
        - field.activity_end
        - field.activity_location
        - field.activity_main_image
        - field.activity_start
        - field.attractentryid
        - field.attractmode
        - field.attractmodeimage
        - field.embed_video
        - field.eventlocation
        - field.has_audio
        - field.host
        - field.milestoneimage
        - field.player_height
        - field.player_width
        - field.readmore
        - field.related_1_class
        - field.related_2_class
        - field.related_3_class
        - field.subtitle
        - field.when
        - field.where
